### ISSUE TITLE
Isn't this the same as DECIMATE modifier?

### ISSUE THREAD

**Issue by megmaltese** [JulienVanelian/lowpolyzer#2]
As per title.

**Comment by JulienVanelian** [comment]
Hello!
It's not the same because the remesh modifier recreates highpoly geometry beforehand, so there is at least some shape maintained after the decimate modifier even for simple meshes (cubes, etc.).

**Comment by megmaltese** [comment]
I can't understand. You have the Remesh modifier in Blender, so you can use that, and then add the Decimate modifier.
I'm missing something?

**Comment by JulienVanelian** [comment]
This is just a one click solution instead of doing what you said and fiddling with parameters, nothing more than that!
